create table car (
gos_number varchar(255) not null,
car_type varchar(255) not null,
model varchar(50) not null,
driver_id integer,
primary key (gos_number)
);

create table driver (
id integer generated by default as identity,
name varchar(50),
driving_license_id integer,
primary key (id)
);

create table driving_license (
id integer generated by default as identity,
categories varchar(255),
number integer not null,
validity_period date,
primary key (id)
);

alter table car add constraint car_driver_fk
foreign key (driver_id) references driver;

alter table driver add constraint driver_driving_license_fk
foreign key (driving_license_id) references driving_license;